force-app/main/default/objects/DE_Credit_Info__mdt.object
<CustomObject>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Utilization__c</fullName>
        <label>Credit Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Due__c</fullName>
        <label>Payment Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Credit Info</label>
    <pluralLabel>Credit Info</pluralLabel>
</CustomObject>

force-app/main/default/objects/Visits__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DE_Credit_Payments_Cntrl.cls
public class DE_Credit_Payments_Cntrl {
    
    @AuraEnabled 
    public static Map<String,object> getCreditInformation(String recordId){
        Map<String,object> returnDataMap = new Map<String,object>();
        List<DE_Credit_Info__mdt> credInfo = [SELECT Credit_Limit__c , Payment_Due__c , Credit_Utilization__c , Due_Date__c 
                                              FROM DE_Credit_Info__mdt LIMIT 1];
        returnDataMap.put('CREDIT_INFO', credInfo);
        Visits__c lVisit = [SELECT Id, Account__r.Name,Account__r.ShippingStreet,Account__r.ShippingCity FROM Visits__c WHERE Id = :recordId];
        returnDataMap.put('VISIT_INFO', lVisit);
        return returnDataMap;
    }
}