force-app/main/default/objects/Visits__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_End__c</fullName>
        <label>Planned End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Planned_Start__c</fullName>
        <label>Planned Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(AND(Checked_In__c == false, Checked_Out__c == false),&apos;Not Started&apos;, IF(AND(Checked_In__c == true, Checked_Out__c == false),&apos;In-Progress&apos;,IF(AND(Checked_In__c == true, Checked_Out__c == true),&apos;Completed&apos;,&apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/upcomingVisitController.cls
public class upcomingVisitController {
    @AuraEnabled
    public static Map<String,List<Visits__c>> getVisits(){ 
        Map<String,List<Visits__c>> visitsMap = new Map<String,List<Visits__c>>();
        visitsMap.put('TODAY',[SELECT Id,Name,Planned_Start__c,Status__c,Lead__r.Name,Lead__r.Company,Planned_End__c,Account__r.Name,Account__r.Id,Account__r.Phone,Account__r.Website,Account__r.ShippingStreet,Account__r.ShippingState,Account__r.ShippingCity,Account__r.ShippingCountry,Account__r.ShippingPostalCode FROM Visits__c WHERE OwnerId = :UserInfo.getUserId() AND DAY_ONLY (Planned_Start__c) = :System.today()]);
        visitsMap.put('TOMORROW',[SELECT Id,Name,Planned_Start__c,Status__c,Lead__r.Name,Lead__r.Company,Planned_End__c,Account__r.Name,Account__r.Id,Account__r.Phone,Account__r.Website,Account__r.ShippingStreet,Account__r.ShippingState,Account__r.ShippingCity,Account__r.ShippingCountry,Account__r.ShippingPostalCode FROM Visits__c WHERE OwnerId = :UserInfo.getUserId() AND DAY_ONLY (Planned_Start__c) = :System.today().addDays(1)]);
        return visitsMap;
    }
}